-- PDBに切り替えて接続する。
ALTER SESSION SET CONTAINER = SCHLPDB;
CONNECT SCHLPDBUSER01/password@SCHLPDB

-- テーブルを作成する。
/*
 * テーブル名：性別
 * 概要：性別に関するデータを格納する。
 */
CREATE TABLE sexes
(
    sex_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 性別ID
    sex_name VARCHAR2(10) NOT NULL UNIQUE -- 性別名(例：男性、女性)
);

/*
 * テーブル名：都道府県
 * 概要：都道府県に関するデータを格納する。
 */
CREATE TABLE prefectures
(
    prefecture_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 都道府県ID
    prefecture_name VARCHAR2(20) NOT NULL UNIQUE -- 都道府県名(例：北海道、東京都、神奈川県、京都府など)
);

/*
 * テーブル名：管理部門
 * 概要：管理者が所属する部署に関するデータを格納する。
 */
CREATE TABLE admin_departments
(
    admin_department_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 管理部門ID
    admin_department_name VARCHAR2(60) NOT NULL, -- 管理部門名
    admin_department_authority CHAR(1) NOT NULL, -- 管理部門権限
    admin_department_status CHAR(1) DEFAULT '0' NOT NULL, -- 管理部門ステータス
    admin_department_created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 管理部門作成日時
    admin_department_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 管理部門更新日時
    admin_department_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 管理部門削除フラグ
    admin_department_deleted_at TIMESTAMP, -- 管理部門削除日時
    CONSTRAINTS check_admin_department_authority CHECK(admin_department_authority IN('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')), -- 0〜9：権限レベル
    CONSTRAINTS check_admin_department_status CHECK(admin_department_status IN('0', '1')), -- 0：無効、1：有効
    CONSTRAINTS check_admin_department_delete_flag CHECK(admin_department_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
* テーブル名：管理者
* 概要：サイト管理者に関するデータを格納する。
 */
CREATE TABLE admins
(
    admin_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 管理者ID
    admin_department_id NUMBER(38, 0) REFERENCES admin_departments(admin_department_id) NOT NULL, -- 管理部門ID
    admin_last_name VARCHAR2(60) NOT NULL, -- 管理者姓
    admin_first_name VARCHAR2(60) NOT NULL, -- 管理者名
    admin_last_name_kana VARCHAR2(120) NOT NULL, -- 管理者姓(フリガナ)
    admin_first_name_kana VARCHAR2(120) NOT NULL, -- 管理者名(フリガナ)
    admin_mail_address VARCHAR2(257) UNIQUE NOT NULL, -- 管理者メールアドレス
    admin_password VARCHAR2(255) NOT NULL, -- 管理者パスワード
    admin_authority CHAR(1) NOT NULL, -- 管理者権限
    admin_status CHAR(1) DEFAULT '0' NOT NULL, -- 管理者ステータス
    admin_created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 管理者作成日時
    admin_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 管理者更新日時
    admin_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 管理者削除フラグ
    admin_deleted_at TIMESTAMP, -- 管理者削除日時
    CONSTRAINTS check_admin_authority CHECK(admin_authority IN('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')), -- 0〜9：権限レベル
    CONSTRAINTS check_admin_status CHECK(admin_status IN('0', '1')), -- 0：無効、1：有効
    CONSTRAINTS check_admin_delete_flag CHECK(admin_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：アカウント
 * 概要：アカウントに関するデータを格納する。
 */
CREATE TABLE accounts
(
    account_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- アカウントID
    last_name VARCHAR2(100) NOT NULL, -- 姓
    first_name VARCHAR2(100) NOT NULL, -- 名
    last_name_kana VARCHAR2(200) NOT NULL, -- 姓(カタカナ)
    first_name_kana VARCHAR2(200) NOT NULL, -- 名(カタカナ)
    sex_id NUMBER(2, 0) REFERENCES sexes(sex_id), -- 性別ID
    birth_date TIMESTAMP, -- 生年月日
    prefecture_id NUMBER(2, 0) NOT NULL REFERENCES prefectures(prefecture_id), -- 都道府県ID
    mail_address VARCHAR2(257) NOT NULL UNIQUE, -- メールアドレス
    profile_image_file_name VARCHAR2(300), -- プロフィール画像ファイル名
    self_introduction VARCHAR2(1000), -- 自己紹介
    password VARCHAR2(256) NOT NULL, -- パスワード
    account_status CHAR(1) DEFAULT '0' NOT NULL, -- アカウントステータス
    activate_token VARCHAR2(256), -- 有効化トークン
    activate_effective_date TIMESTAMP, -- 有効化トークン有効期限
    reissue_token VARCHAR2(256), -- 再発行トークン
    reissue_effective_date TIMESTAMP, -- 再発行トークン有効期限
    account_created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- アカウント作成日時
    account_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- アカウント更新日時
    account_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- アカウント削除フラグ
    account_deleted_at TIMESTAMP, -- アカウント削除日時
    CONSTRAINTS check_account_status CHECK(account_status IN('0', '1')), -- 0：無効、1：有効
    CONSTRAINTS check_account_delete_flag CHECK(account_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：カテゴリー
 * 概要：スクールに設定するカテゴリーに関するデータを格納する。
 */
CREATE TABLE categories
(
    category_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- カテゴリーID
    category_name VARCHAR2(200) NOT NULL UNIQUE, -- カテゴリー名
    senior_category_id NUMBER(38, 0), -- 上位カテゴリーID
    category_status CHAR(1) DEFAULT '0' NOT NULL, -- カテゴリーステータス
    category_created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- カテゴリー作成日時
    category_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- カテゴリー更新日時
    category_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 削除フラグ
    category_deleted_at TIMESTAMP, -- カテゴリー削除フラグ更新日時
    CONSTRAINTS check_category_status CHECK(category_status IN('0', '1')), -- 0：無効、1：有効
    CONSTRAINTS check_category_delete_flag CHECK(category_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：スクール
 * 概要：スクールに関するデータを格納する。
 */
CREATE TABLE schools
(
    school_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- スクールID
    registrant_account_id NUMBER(38, 0) REFERENCES accounts(account_id), -- 登録者アカウントID
    registrant_admin_id NUMBER(38, 0) REFERENCES admins(admin_id), -- 登録者管理者ID
    school_name VARCHAR2(200) NOT NULL, -- スクール名
    school_category_id NUMBER(38, 0) NOT NULL REFERENCES categories(category_id), -- スクールカテゴリーID
    school_summary VARCHAR2(500) NOT NULL, -- スクール概要
    school_description VARCHAR2(4000) NOT NULL, -- スクール詳細
    school_zip_code1 VARCHAR2(3) NOT NULL, -- スクール郵便番号1
    school_zip_code2 VARCHAR2(4) NOT NULL, -- スクール郵便番号2
    school_prefecture_id NUMBER(2, 0) NOT NULL REFERENCES prefectures(prefecture_id), -- スクール都道府県ID
    school_city VARCHAR2(70) NOT NULL, -- スクール市区町村
    school_address1 VARCHAR2(500) NOT NULL, -- スクール住所1
    school_address2 VARCHAR2(500), -- スクール住所2
    school_fee NUMBER(15, 0) NOT NULL, -- スクール費用
    supplementary_fee VARCHAR2(500), -- 費用補足
    school_url VARCHAR2(300), -- スクールサイトURL
    school_release_propriety CHAR(1) DEFAULT '0' NOT NULL, -- スクール公開可否
    school_entry_propriety CHAR(1) DEFAULT '0' NOT NULL, -- スクール申込可否
    summary_image_file_name VARCHAR2(300), -- 一覧画面画像ファイル名
    detail_image1_file_name VARCHAR2(300), -- 詳細画面画像1ファイル名
    detail_image2_file_name VARCHAR2(300), -- 詳細画面画像2ファイル名
    detail_image3_file_name VARCHAR2(300), -- 詳細画面画像3ファイル名
    detail_image4_file_name VARCHAR2(300), -- 詳細画面画像4ファイル名
    detail_image5_file_name VARCHAR2(300), -- 詳細画面画像5ファイル名
    detail_image6_file_name VARCHAR2(300), -- 詳細画面画像6ファイル名
    detail_image7_file_name VARCHAR2(300), -- 詳細画面画像7ファイル名
    detail_image8_file_name VARCHAR2(300), -- 詳細画面画像8ファイル名
    school_registered_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- スクール登録日時
    school_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- スクール更新日時
    school_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- スクール削除フラグ
    school_deleted_at TIMESTAMP, -- スクール削除フラグ更新日時
    CONSTRAINTS check_account_id_or_admin_id CHECK(registrant_account_id IS NOT NULL OR registrant_admin_id IS NOT NULL), -- 登録者アカウントIDまたは登録者管理者IDのいずれか一方はNULL不可
    CONSTRAINTS check_entry_propriety CHECK(school_entry_propriety IN('0', '1')), -- 0：不可、1：可
    CONSTRAINTS check_release_propriety CHECK(school_release_propriety IN('0', '1')), -- 0：不可、1：可
    CONSTRAINTS check_school_delete_flag CHECK(school_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：申込ステータス
 * 概要：申込ステータスに関するデータを格納する。
 */
CREATE TABLE entry_statuses
(
    entry_status_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 申込ステータスID
    entry_status_name VARCHAR2(20) NOT NULL UNIQUE -- 申込ステータス名(例：申込済、連絡済、キャンセル済など)
);

/*
 * テーブル名：申込
 * 概要：スクールへの申込に関するデータを格納する。
 */
CREATE TABLE entries
(
    entry_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 申込ID
    entry_school_id NUMBER(38, 0) NOT NULL REFERENCES schools(school_id), -- 申込先スクールID
    applicant_account_id NUMBER(38, 0) NOT NULL REFERENCES accounts(account_id), -- 申込者アカウントID
    entry_question VARCHAR2(3500), -- 質問
    entry_status_id NUMBER(1, 0) NOT NULL REFERENCES entry_statuses(entry_status_id), -- 申込ステータスID
    entried_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 申込日時
    entry_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 申込更新日時
    entry_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 申込削除フラグ
    entry_deleted_at TIMESTAMP, -- 申込削除日時
    CONSTRAINTS check_entry_delete_flag CHECK(entry_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：お気に入り
 * 概要：お気に入りスクールのデータを格納する。
*/
CREATE TABLE favorites
(
    favorite_id NUMBER(38, 0) PRIMARY KEY, -- お気に入りID
    account_id NUMBER(38, 0) NOT NULL REFERENCES accounts(account_id), -- アカウントID
    school_id NUMBER(38, 0) NOT NULL REFERENCES schools(school_id), -- スクールID
    favorite_added_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL -- お気に入り追加日時
);

/*
 * テーブル名：メッセージ
 * 概要：スクールに申し込んだアカウントと受け付けたアカウントが相互にやり取りするメッセージに関するデータを格納する。
 */
CREATE TABLE messages
(
    message_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- メッセージID
    reply_message_id NUMBER(38, 0) REFERENCES messages(message_id), -- 返信メッセージID ※返信するメッセージのメッセージID
    entry_id NUMBER(38, 0) NOT NULL REFERENCES entries(entry_id), -- 申込ID
    sender_account_id NUMBER(38, 0) NOT NULL REFERENCES accounts(account_id), -- 差出アカウントID
    recipient_account_id NUMBER(38, 0) NOT NULL REFERENCES accounts(account_id), -- 受取アカウントID
    message_subject VARCHAR2(90) NOT NULL, -- 件名
    message_body VARCHAR2(3500) NOT NULL, -- 本文
    sended_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 送信日時
    opened_flag CHAR(1) DEFAULT '0' NOT NULL, -- 開封済フラグ
    opened_at TIMESTAMP, -- 開封日時
    sender_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 差出アカウント側削除フラグ
    sender_flag_updated_at TIMESTAMP, -- 差出アカウント側削除フラグ更新日時
    recipient_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- 受取アカウント側削除フラグ
    recipient_flag_updated_at TIMESTAMP, -- 受取アカウント側削除フラグ更新日時
    CONSTRAINTS check_opened_flag CHECK(opened_flag IN('0', '1')), -- 0：開封済、1：未開封
    CONSTRAINTS check_sender_delete_flag CHECK(sender_delete_flag IN('0', '1')), -- 0：未削除、1：削除
    CONSTRAINTS check_recipient_delete_flag CHECK(recipient_delete_flag IN('0', '1')) -- 0：未削除、1：削除
);

/*
 * テーブル名：お問合せステータス
 * 概要：お問合せステータスに関するデータを格納する。
 */
CREATE TABLE contact_statuses
(
    contact_status_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- お問合せステータスID
    contact_status_name VARCHAR2(20) NOT NULL UNIQUE -- お問合せステータス名(例：受付済、連絡済など)
);

/*
 * テーブル名：お問合せ
 * 概要：お問合せに関するデータを格納する。
 */
CREATE TABLE contacts
(
    contact_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- お問合せID
    contact_account_id NUMBER(38, 0) REFERENCES accounts(account_id), -- お問合せ者アカウントID
    contact_last_name VARCHAR2(100) NOT NULL, -- お問合せ者姓
    contact_first_name VARCHAR2(100) NOT NULL, -- お問合せ者名
    contact_last_name_kana VARCHAR2(200) NOT NULL, -- お問合せ者姓(フリガナ)
    contact_first_name_kana VARCHAR2(200) NOT NULL, -- お問合せ者名(フリガナ)
    contact_mail_address VARCHAR2(256) NOT NULL, -- お問合せ者メールアドレス
    contact_content VARCHAR2(3500) NOT NULL, -- お問合せ内容
    contact_status_id NUMBER(2, 0) NOT NULL REFERENCES contact_statuses(contact_status_id), -- お問合せステータスID
    contacted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- お問合せ日時
    contact_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- お問合せ更新日時
    contact_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- お問合せ削除フラグ
    contact_deleted_at TIMESTAMP, -- お問合せ削除日時
    CONSTRAINTS check_contact_delete_flag CHECK(contact_delete_flag IN('0', '1')) -- 0：未削除,1：削除
);

/*
 * テーブル名：メールテンプレート
 * 概要：システムが送信するメールのテンプレートに関するデータを格納する。
 */
CREATE TABLE mail_templetes
(
    mail_templete_id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- メールテンプレートID
    mail_templete_name VARCHAR2(120) UNIQUE NOT NULL, -- メールテンプレート名
    mail_templete_subject VARCHAR2(120) NOT NULL, -- 件名
    mail_templete_header VARCHAR2(600) NOT NULL, -- ヘッダー文
    mail_templete_footer VARCHAR2(600) NOT NULL, -- フッター文
    mail_templete_created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- メールテンプレート作成日時
    mail_templete_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- メールテンプレート更新日時
    mail_templete_delete_flag CHAR(1) DEFAULT '0' NOT NULL, -- メールテンプレート削除フラグ
    mail_templete_deleted_at TIMESTAMP, -- メールテンプレート削除日時
    CONSTRAINTS check_mail_templete_delete_flag CHECK(mail_templete_delete_flag IN('0', '1')) -- 0：未削除,1：削除
);
